import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} h-screen antialiased flex justify-between`}>
        <aside className="h-full p-5 w-1/4">
          <nav className="h-full text-amber-500">
            <input
              className="outline-0 border-2 border-amber-500 rounded-2xl w-full h-1/20 indent-2"
              type="text"
              placeholder="Search"
            />
            <ul className="h-fit">
              <li className="h-15 w-full flex items-center hover:bg-amber-500 hover:text-amber-950 rounded-2xl">
                <Link href="/chat/1/" className="h-full w-full p-5 flex items-start rounded-2xl">Verttra</Link>
              </li>
            </ul>
          </nav>
        </aside>
        {children}
      </body>
    </html>
  );
}
